site_name: Jacob Chef Automation Book
site_description: "Jacob's Chef Automation 技术与实战教程"
site_author: "Jacob Xi"
copyright: "Copyright &copy; 2021-9999 Jacob Xi"

plugins:
  - search # necessary for search to work
  - awesome-pages

nav:
  - 'Welcome': "index.md"
  - 'Learning Chef':
    - '第一节 Chef 介绍和安装': 'chap1/chef_tutorial1.md'
    - '第二节 Ruby和Chef语法': 'chap1/chef_tutorial2.md'
    - '第三节 如何写 Chef 配方 & chef-apply' :

repo_url: https://github.com/Chao-Xi/jxchefbook.git
repo_name: "jxchefbook"

theme: 
  language: zh
  name: 'material'
  include_sidebar: true
  logo: 'images/logo.png'
  favicon: 'images/logo.png'
  feature:
    tabs: false
  palette:
    primary: 'deep orange'
    accent: 'deep orange'
  i18n:
    prev: 'Previous'
    next: 'Next'