site_name: Jacob Chef&Ansible Automation Book
site_description: "Jacob's Chef&Ansible Automation 技术与实战教程"
site_author: "Jacob Xi"
copyright: "Copyright &copy; 2021-9999 Jacob Xi"

plugins:
  - search # necessary for search to work
  - awesome-pages

nav:
  - 'Welcome': "index.md"
  - 'Learning Chef':
    - '第一节 Chef 介绍和安装': 'chap1/chef_tutorial1.md'
    - '第二节 Ruby和Chef语法': 'chap1/chef_tutorial2.md'
    - '第三节 如何写 Chef 配方 & chef-apply': 'chap1/chef_tutorial3.md'
    - '第四节 用Test Kitchen管理沙盒测试环境': 'chap1/chef_tutorial4.md'
    - '第五节 用 Chef 户端管理节点': 'chap1/chef_tutorial5.md'
    - '第六节 撰写和使用菜谱': 'chap1/chef_tutorial6.md'
    - '第七节 Chef 属性': 'chap1/chef_tutorial7_attributes.md'
    - '第八节 Chef 服务器同时管理多个节点': 'chap1/chef_tutorial8.md'
    - '第九节 社区以及Chef-Client菜谱': 'chap1/chef_tutorial9.md'
    - '第十节 Chef zero': 'chap1/chef_tutorial10_zero.md'
    - '第十一节 数概包Databag': 'chap1/chef_tutorial11_databag.md'
    - '第十二节 角色': 'chap1/chef_tutorial12.md'
    - '第十三节 环境': 'chap1/chef_tutorial13_env.md'
    - '第十四节 测试': 'chap1/chef_tutorial14_test.md'
    - '第十五节 词汇表': 'chap1/chef_tutorial15_term.md'
    - '第十六节 Chef Tutorial Interview': 'chap1/chef_tutorial16_int.md'
  - 'Chef Opt & Adv':
    - '第一节 Chef Roles': 'chap2/chef_adv4.md'
    - '第二节 Cookbook Versioning': 'chap2/chef_adv5.md'
    - '第三节 How to Perform Chef Knife SSL Check and Fetch to Verify Certificate': 'chap2/chef_adv1.md'
    - '第四节 12 Chef Knife Cookbook Command Examples': 'chap2/chef_adv2.md'
    - '第五节 knife search': 'chap2/chef_op1_kinfe_search.md'
    - '第六节 Chef Quick CheatSheet': 'chap2/chef_adv3.md'
  - 'Chef Cookbook Sample LAMP':
    - '第一节 Creating My First Chef Cookbook': 'chap3/chef_basic5.md'
    - '第二节 Creating LAMP Chef Cookbook Analysis': 'chap3/chef_basic6.md'
  - 'Learning Ansible':
    - 'L1 Ansible Introduction': 'chap4/1ansible_intro.md'
    - 'L2 Ansible Install(MacOs) and Environment Setup': 'chap4/2ansible_over_install.md'
    - 'L3 Task Execution management': 'chap4/3play_task.md'
    - 'L4 Ansible Variable Management': 'chap4/4Ansible_variables.md'
    - 'L5 Managing complex playbooks with roles and ansible galaxy': 'chap4/5Complex_roles.md'
    - 'L6 Working with Secrets': 'chap4/6Secret_management.md'
    - 'L7 Network Management with Ansible': 'chap4/7Network_management.md'
    - 'L8 Idempotentence with Ansible play': 'chap4/8idempotentence.md'
    - 'L9 Ansible Interview': 'chap4/9Ansible_interview.md'
    - 'L10 Ansible 自动化运维工具PPT': 'chap4/10Ansible_learn_ppt.md' 
    - 'L11 任务中心之Ansible基础篇': 'chap4/11Ansible_task1.md'
    - 'L12 任务中心之Ansible进阶篇': 'chap4/12Ansible_task2.md'
    - 'L13 Ansible 面试知识点': 'chap4/13Ansible_int.md'
  - 'HashiCorp Certified Terraform Associate':
    - 'HashiCorp Certified Terraform Associate Learning Path': 'chap5/1hashicorp_certified_terraform.md'
    - 'Terraform Cheat Sheet': 'chap5/2terraform_cs.md'
    - '.terraform.lock.hcl 简介': 'chap5/3terraform_lock.md'
    - 'terraform.tfvars 与 variables.tf 的区别': 'chap5/4terraform_var.md'
    - 'Terraform: Random 简介': 'chap5/5terraform_random.md'
    - 'Top Terraform Interview Questions and Answers (2022)': 'chap5/6terraform_int.md'
    - 'Terraform provider update': 'chap5/7terraform_provider.md'
    - 'Terraform install Jenkins in Docker': 'chap5/8terraform_docker_jenkins.md'
    - '解决Terraform初始化慢~配置本地离线源': 'chap5/9terraform_local.md'
  - 'Puppet Learning':
    - '1 Puppet - Overview & Architecture': 'chap5/1pp_overview.md'
    - '2 Puppet - 安装, 配置以及验证': 'chap5/2pp_install_config.md'

repo_url: https://github.com/Chao-Xi/jxchefbook.git
repo_name: "jxchefbook"

theme: 
  language: zh
  name: 'material'
  include_sidebar: true
  logo: 'images/logo.png'
  favicon: 'images/logo.png'
  feature:
    tabs: false
  palette:
    primary: 'deep orange'
    accent: 'deep orange'
  i18n:
    prev: 'Previous'
    next: 'Next'